# Generated by Django 6.0.1 on 2026-01-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignment_options_alter_submission_options_and_more'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-graded_at'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, help_text='Instructor feedback', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='instructor',
            field=models.ForeignKey(help_text='Instructor who graded the submission', on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(blank=True, help_text='Letter grade (e.g., A, B, C)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric score (e.g., 85.50)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='submission',
            field=models.OneToOneField(help_text='Submission being graded', on_delete=django.db.models.deletion.CASCADE, related_name='grade_record', to='assignments.submission'),
        ),
    ]
