# Generated by Django 6.0.1 on 2026-01-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='grade',
        ),
    ]
