# Generated by Django 6.0.1 on 2026-01-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_due_date'),
        ('courses', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('course', 'title')},
        ),
    ]
