# Generated by Django 4.2.27 on 2026-01-27 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numeric score (e.g., 85.50)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        blank=True,
                        help_text="Letter grade (e.g., A, B, C)",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Instructor feedback", null=True
                    ),
                ),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Instructor who graded the submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="Submission being graded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_record",
                        to="assignments.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["-graded_at"],
            },
        ),
    ]
